---
- name: num Page
  hosts: g1
  become: yes
  vars:
    myusername: Anita

  tasks:
    - name: Update Unique Page
      template:
        src: dynamic.jinja2
        dest: /var/www/html/dynamic.html
        ...