---
- name: Num Page
  hosts: g1
  become: yes
  vars:
    myusername: Anita

  tasks:
    - name: Update Dynamic Page
      template:
        src: dynamic.jinja2
        dest: /var/www/html/dynamic.html
...