---
- name: Deploy Static Page
  hosts: g1
  become: yes

  tasks:
    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy Static HTML File
      copy:
        src: static.html
        dest: /var/www/html/index.html
...
